-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: f82fb149af2c1b552b50e3e38e38ed3a44d4cda1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git@github.com:asottile/reorder_python_imports
    sha: f3dfe379d2ea341c6cf54d926d4585b35dea9251
    hooks:
    -   id: reorder-python-imports
        exclude: ^bench/
