-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 35548254adb636ce52b5574eb1904b8c795b673e
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    sha: 017e2f64306853ec7f000db52b8280da27eb3b96
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories', '.:bench']
